name: ARM (Raspberry Pi)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      with:
        commands: |
            sudo apt install python3 python3-pip
            pip3 install -r requirements.txt
            make test
