name: ARM (Raspberry Pi)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: dietpi:rpi_armv8_bullseye
        commands: |
            sudo apt install -y python3 python3-pip
            pip3 install -r requirements.txt
            make test
